Lmagniez
INSSET/UE-QC-PHPCS pull request #10
Opened 2022-03-29 12:43 UTC by LaetitiaMagniez

Modification des fichiers qui ne passaient pas les tests

2022-03-29 12:51 UTC, trannois requested changes
L'exemple d'utilisation de ton formulaire ne fonctionne pas
Le fichier form_xxxx doit se trouver dans le répertoire exemple et avoir .html comme extension

2022-03-29 12:54 UTC, trannois commented
Il faut aussi que tu prennes en compte les ajouts des autres collaborateurs sur dev
$ git checkout dev
$ git pull
$ git checkout (mabranche)
$ git rebase dev

2022-03-29 12:56 UTC, LaetitiaMagniez commented
d'accord merci

Le mar. 29 mars 2022 à 14:54, Trannois Harold ***@***.***> a
écrit :

> Il faut aussi que tu prennes en compte les ajouts des autres
> collaborateurs sur dev
> $ git checkout dev
> $ git pull
> $ git checkout (mabranche)
> $ git rebase dev
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/INSSET/UE-QC-PHPCS/pull/10#issuecomment-1081835248>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARL3TUAIZUK5Z4MLAFRR6VLVCL4P5ANCNFSM5R6JDEVA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-29 13:03 UTC, LaetitiaMagniez commented
je dois " rebase dev onto" ma branche c'est ça ? ou seulement faire git
rebase dev ?

Le mar. 29 mars 2022 à 14:56, Laëtitia Magniez ***@***.***> a
écrit :

> d'accord merci
>
> Le mar. 29 mars 2022 à 14:54, Trannois Harold ***@***.***>
> a écrit :
>
>> Il faut aussi que tu prennes en compte les ajouts des autres
>> collaborateurs sur dev
>> $ git checkout dev
>> $ git pull
>> $ git checkout (mabranche)
>> $ git rebase dev
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/INSSET/UE-QC-PHPCS/pull/10#issuecomment-1081835248>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ARL3TUAIZUK5Z4MLAFRR6VLVCL4P5ANCNFSM5R6JDEVA>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2022-03-29 13:10 UTC, trannois commented
Quand tu est sur ta branche tu fais juste un
$ git rebase dev
pour que ta branche reparte du dernier commit de dev

2022-03-29 13:10 UTC, trannois commented
ensuite quand tu as repushé ta branche tu peux redemander une review

2022-03-29 13:12 UTC, LaetitiaMagniez commented
ok merci beaucoup !

Le mar. 29 mars 2022 à 15:11, Trannois Harold ***@***.***> a
écrit :

> ensuite quand tu as repushé ta branche tu peux redemander une review
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/INSSET/UE-QC-PHPCS/pull/10#issuecomment-1081852803>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARL3TUCSV26JYO24LAFBZMTVCL6OZANCNFSM5R6JDEVA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-29 13:42 UTC, LaetitiaMagniez commented
j'ai re push ma branche, normalement tout est ok

2022-04-26 07:31 UTC, trannois commented
Le validateur n'est pas opérationnel, il y a des erreurs :
file_get_contents(/projet/public/../conf/**Laëtitia_EstUneImage.json)**: Failed to open stream: No such file or directory in /projet/public/traite.php on line 19

2022-04-26 07:31 UTC, closed without merging